name: Run NCEP tests

on:
  push:
    branches:
      - InAir_Dev
  pull_request:
    branches:
      - InAir_Dev

jobs:
  test_ncep:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: ci/requirements/py3.11-all-pinned.yml
          auto-activate-base: false
          activate-environment: pydox-dev


      #- name: Setup Python
      #  uses: actions/setup-python@v6
      #  with:
      #    python-version: ${{ matrix.python-version }}

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install pytest

      #- name: Run test NCEP IO.py
      #  run: pytest tests/test_io.py -v -k 'ncep' --cov=io --cov-report=xml --cov-report=term-missing

      - name: Run NCEP test IO
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          conda activate pydox-dev
          pytest pydox/tests/test_io.py -v -k 'ncep' --cov=pydox/io --cov-report=xml:coverage.xml --cov-report=term-missing --junitxml=test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.xml