name: Run NCEP tests

on:
  push:
    branches:
      - InAir_Dev
  pull_request:
    branches:
      - InAir_Dev

jobs:
  test_ncep:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ "3.11"]

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # Force to use Node.js 24
      #ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true # Force to Node.js 20 (node 20 will be unavailable at 2026 end)

    steps:
      - name: Check Node version
        run: node -v

      - name: Checkout repo
        uses: actions/checkout@v6

      #- name: Setup Miniconda
      #  uses: conda-incubator/setup-miniconda@v4
      #  with:
      #    environment-file: ci/requirements/py3.11-all-pinned.yml
      #    auto-activate: true
      #    activate-environment: pydox-dev

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/requirements/py3.11-all-pinned.yml
          environment-name: pydox-dev
          init-shell: bash
          cache-environment: true # change to false to remove mamba env. in the cache
                                  # When true, github save the env. in the cache.
                                  # The first run can be long, the following are faster

      #- name: Setup Python
      #  uses: actions/setup-python@v6
      #  with:
      #    python-version: ${{ matrix.python-version }}

      #- name: Install dependencies
      #  run: |
      #    python -m pip install --upgrade pip
      #    pip install pytest

      #- name: Run test NCEP IO.py
      #  run: pytest tests/test_io.py -v -k 'ncep' --cov=io --cov-report=xml --cov-report=term-missing

      #- name: Set environment variables for Windows ($HOME automatically defined for linux/macOs)
      #  if: runner.os == 'Windows'
      #  run: |
      #    setx HOME "C:\Users\runneradmin"
      #    setx USER "runneradmin"

      - name: Run NCEP test IO
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          pytest pydox/tests/test_io.py -v -k 'ncep' --cov=pydox/io --cov-report=xml:coverage.xml --cov-report=term-missing --junitxml=test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload test results
        uses: actions/upload-artifact@v6
        with:
          name: pytest-results
          path: test-results.xml